### PR TITLE
Added Composer, Spelling, Docstrings, PSR-4

### PR DESCRIPTION
**Pull request by sifex**
Essentially changed the package to the common PHP standard package layout. Main feature points are

- Namespacing / PSR-4 Standard
- composer.json added (Please let me know if the licence / details are incorrect)
- Docstrings for methods

### CODE REVIEW

**Comment by flowdee** [comment]
Would be great to get this merged asap

**Comment by LucasGorgal** [comment]
Apparently it will never be merged

**Comment by sifex** [comment]
Happy to ping @DejanPelzel 😄

**Comment by sifex** [comment]
Shameless plug for the unofficial FlySystem Adapter in lieu of this repo receiving any updates.

👉🏼 https://github.com/PlatformCommunity/flysystem-bunnycdn

**Comment by rafael-at-bunny** [comment]
This has been addressed in the [2.0.0 release](https://github.com/BunnyWay/BunnyCDN.PHP.Storage/releases/tag/2.0.0). Thank you.

**Pull request closed without merging**
